#pragma once
#include "public_definitions.h"

enum ClientProperties {
    CLIENT_UNIQUE_IDENTIFIER = 0,
    CLIENT_NICKNAME,
    CLIENT_VERSION,
    CLIENT_PLATFORM,
    CLIENT_FLAG_TALKING,
    CLIENT_INPUT_MUTED,
    CLIENT_OUTPUT_MUTED,
    CLIENT_INPUT_HARDWARE,
    CLIENT_OUTPUT_HARDWARE,
    CLIENT_INPUT_DEACTIVATED,
    CLIENT_IDLE_TIME,
    CLIENT_DEFAULT_CHANNEL,
    CLIENT_DEFAULT_CHANNEL_PASSWORD,
    CLIENT_SERVER_PASSWORD,
    CLIENT_META_DATA,
    CLIENT_IS_MUTED,
    CLIENT_IS_RECORDING,
    CLIENT_VOLUME_MODIFICATOR,
    CLIENT_ENDMARKER
};

enum ChannelProperties {
    CHANNEL_NAME = 0,
    CHANNEL_TOPIC,
    CHANNEL_DESCRIPTION,
    CHANNEL_PASSWORD,
    CHANNEL_CODEC,
    CHANNEL_CODEC_QUALITY,
    CHANNEL_MAXCLIENTS,
    CHANNEL_MAXFAMILYCLIENTS,
    CHANNEL_ORDER,
    CHANNEL_FLAG_PERMANENT,
    CHANNEL_FLAG_SEMI_PERMANENT,
    CHANNEL_FLAG_DEFAULT,
    CHANNEL_FLAG_PASSWORD,
    CHANNEL_CODEC_LATENCY_FACTOR,
    CHANNEL_CODEC_IS_UNENCRYPTED,
    CHANNEL_ENDMARKER
};
